[package]
name = "nodesea"
version = "0.0.1"
edition = "2024"
license = "MIT"
authors = ["HualiNox"]
readme = "README.md"

[workspace]
resolver = "2"
members = ["crates/nodesea-bt", "crates/nodesea-daemon"]

[workspace.package]
version = "0.0.1"
authors = ["HualiNox"]
license = "MIT"
edition = "2024"

[workspace.dependencies]
anyhow = "1"
tokio = { version = "1.53.1", features = ["full"] }

[dependencies]
nodesea-daemon = { path = "crates/nodesea-daemon" }
tokio.workspace = true
tracing = "0.1.44"
tracing-subscriber = "0.3.23"

[target.'cfg(target_os = "linux")'.dependencies]
libc = "0.2.189"

[[bin]]
name = "nodesead"
path = "src/bin/nodesead.rs"
