[package]
name = "nodesea-daemon"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
thiserror.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
nodesea-bt.workspace = true
nodesea-proto.workspace = true
nodesea-helper.workspace = true
tonic.workspace = true
tracing = "0.1.44"

[target.'cfg(unix)'.dependencies]
libc = "0.2.189"
