[package]
name = "nodesea-cli"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
hyper-util.workspace = true
nodesea-proto.workspace = true
nodesea-helper.workspace = true
rust-i18n = "4.2.1"
sys-locale = "0.3.2"
tokio.workspace = true
tonic.workspace = true
tower = "0.5.3"
ratatui = "0.30.2"
crossterm = "0.29.0"
