use rand::RngExt;

/// The number of bytes in a node identifier.
pub(crate) const NODE_ID_BYTES: usize = 20;

/// Metadata for a node in the DHT.
///
/// It contains a NodeID, address, and port number.
#[derive(Clone, Debug)]
pub struct Node {
    id: NodeID,
    address: String,
    port: u16,
}

/// A 20-byte identifier for a node in the DHT.
///
/// It is used to identify nodes on the network and is stored in the routing table.
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub struct NodeID([u8; NODE_ID_BYTES]);

impl Node {
    /// Creates a node with a randomly generated [`NodeID`].
    ///
    /// The identifier is generated by filling a 20-byte array with random
    /// bytes.
    ///
    /// # Arguments
    ///
    /// * `address` - The node's network address.
    /// * `port` - The node's network port.
    ///
    /// # Returns
    ///
    /// A node with a random identifier and the supplied network endpoint.
    ///
    /// # Examples
    ///
    /// ```
    /// use nodesea::dht::Node;
    ///
    /// let node = Node::random("127.0.0.1".to_string(), 8080);
    /// ```
    pub fn random(address: String, port: u16) -> Self {
        Self {
            id: NodeID::random(),
            address,
            port,
        }
    }

    /// Creates a node with an existing identifier and network endpoint.
    ///
    /// # Arguments
    ///
    /// * `id` - The node's identifier.
    /// * `address` - The node's network address.
    /// * `port` - The node's network port.
    ///
    /// # Returns
    ///
    /// A node with the supplied identifier and network endpoint.
    ///
    /// # Examples
    ///
    /// ```
    /// use nodesea::dht::Node;
    /// use nodesea::dht::NodeID;
    ///
    /// let node = Node::from_id(NodeID::random(), "127.0.0.1".to_string(), 8080);
    /// ```
    pub fn from_id(id: NodeID, address: String, port: u16) -> Self {
        Self { id, address, port }
    }

    /// Returns the node's identifier.
    ///
    /// # Returns
    ///
    /// A reference to this node's [`NodeID`].
    pub fn id(&self) -> &NodeID {
        &self.id
    }

    /// Returns the node's network address.
    ///
    /// # Returns
    ///
    /// A string slice containing the node's network address.
    pub fn address(&self) -> &str {
        &self.address
    }

    /// Returns the node's network port.
    ///
    /// # Returns
    ///
    /// The node's network port.
    pub fn port(&self) -> u16 {
        self.port
    }
}

impl NodeID {
    /// Creates a randomly generated node identifier.
    ///
    /// The identifier is generated by filling a 20-byte array with random
    /// bytes.
    ///
    /// # Returns
    ///
    /// A randomly generated [`NodeID`].
    pub fn random() -> Self {
        let mut id = [0u8; NODE_ID_BYTES];
        rand::rng().fill(&mut id);
        Self(id)
    }

    /// Calculates the XOR distance to another node identifier.
    ///
    /// The distance is calculated byte by byte using bitwise XOR:
    ///
    /// ```text
    /// d = self ^ other
    /// ```
    ///
    /// # Arguments
    ///
    /// * `other` - The other `NodeID` to calculate the distance to.
    ///
    /// # Returns
    ///
    /// A 20-byte array containing the XOR distance.
    pub fn distance(&self, other: &NodeID) -> [u8; NODE_ID_BYTES] {
        std::array::from_fn(|index| self.0[index] ^ other.0[index])
    }

    /// Creates a node identifier from its raw 20-byte representation.
    ///
    /// # Arguments
    ///
    /// * `node_id` - The raw 20-byte identifier.
    ///
    /// # Returns
    ///
    /// A node identifier containing the supplied bytes.
    pub fn from_id(node_id: [u8; NODE_ID_BYTES]) -> Self {
        NodeID(node_id)
    }

    /// Returns the raw bytes of the node identifier.
    ///
    /// # Returns
    ///
    /// A reference to the identifier's 20-byte representation.
    pub fn node_id(&self) -> &[u8; NODE_ID_BYTES] {
        &self.0
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_new() {
        let id = NodeID::random();
        assert_eq!(id.0.len(), NODE_ID_BYTES);
    }

    #[test]
    fn test_node_accessors() {
        let id = NodeID::from_id([0; NODE_ID_BYTES]);
        let node = Node::from_id(id, "127.0.0.1".to_string(), 8080);

        assert_eq!(node.address(), "127.0.0.1");
        assert_eq!(node.port(), 8080);
    }

    #[test]
    fn test_distance() {
        let id1 = NodeID([0; NODE_ID_BYTES]);

        let mut data = [0u8; NODE_ID_BYTES];
        data[NODE_ID_BYTES - 1] = 1;

        let id2 = NodeID(data);

        assert_eq!(id1.distance(&id2), data);
    }
}
