//! Observe DHT activity generated by the local libtorrent session.

use nodesea_bt::{
    AlertCategory, BoolSetting, BtEvent, Engine, EngineExtension, IntSetting, SettingsPack,
    StringSetting,
};

const BOOTSTRAP_NODES: &str =
    "dht.libtorrent.org:25401,router.bittorrent.com:6881,dht.transmissionbt.com:6881";

/// Prints DHT alerts without issuing explicit DHT requests through the engine.
struct DhtObserver;

impl EngineExtension for DhtObserver {
    fn on_event(&mut self, event: &BtEvent) {
        println!("{:?}", event);
    }
}

#[tokio::main(flavor = "current_thread")]
async fn main() {
    let alert_mask = AlertCategory::DHT_LOG_NOTIFICATION;
    let mut settings = SettingsPack::new();
    settings.set_bool(BoolSetting::EnableDht, true);
    settings.set_int(IntSetting::AlertMask, alert_mask);
    settings.set_string(StringSetting::ListenInterfaces, "0.0.0.0:0,[::]:0");
    settings.set_string(StringSetting::DhtBootstrapNodes, BOOTSTRAP_NODES);

    // libtorrent performs the initial bootstrap from the configured nodes.
    let engine = Engine::builder()
        .set_settings_pack(settings)
        .add_extension(DhtObserver)
        .build();

    // Start the session and print alerts delivered to the extension.
    engine
        .run()
        .await
        .expect("engine runner stopped unexpectedly");
}
