//! Observe DHT activity generated by the local libtorrent session.
use std::time::UNIX_EPOCH;

use nodesea_bt::{
    AlertCategory, BoolSetting, BtEvent, BtEventKind, Engine, EventSink, IntSetting, SettingsPack,
    StringSetting,
};

const BOOTSTRAP_NODES: &str =
    "dht.libtorrent.org:25401,router.bittorrent.com:6881,dht.transmissionbt.com:6881";

/// Prints DHT alerts without issuing explicit DHT requests through the engine.
struct DhtObserver;

impl EventSink for DhtObserver {
    fn on_event(&mut self, event: BtEvent) {
        print!(
            "timestamp: {} ",
            event
                .timestamp()
                .duration_since(UNIX_EPOCH)
                .expect("system time is before Unix epoch")
                .as_micros()
        );
        match event.kind() {
            BtEventKind::DhtBootstrap(_) => {
                println!("dht bootstrap completed");
            }
            BtEventKind::DhtAnnounce(event) => {
                println!(
                    "dht announce: info_hash={} peer={}:{}",
                    event.info_hash(),
                    event.peer_ip(),
                    event.peer_port()
                );
            }
            BtEventKind::DhtGetPeers(event) => {
                println!("dht get_peers: info_hash={}", event.info_hash());
            }
            BtEventKind::DhtError(event) => {
                println!("dht error: {}", event.message());
            }
            _ => {}
        }
    }
}

fn main() {
    let alert_mask = AlertCategory::DHT_NOTIFICATION | AlertCategory::ERROR_NOTIFICATION;
    let mut settings = SettingsPack::new();
    settings.set_bool(BoolSetting::EnableDht, true);
    settings.set_int(IntSetting::AlertMask, alert_mask);
    settings.set_string(StringSetting::ListenInterfaces, "0.0.0.0:0,[::]:0");
    settings.set_string(StringSetting::DhtBootstrapNodes, BOOTSTRAP_NODES);

    // libtorrent performs the initial bootstrap from the configured nodes.
    let mut engine = Engine::builder()
        .set_settings_pack(settings)
        .build()
        .expect("failed to initialize engine");
    let mut observer = DhtObserver;

    // Poll and print alerts generated by the session.
    loop {
        engine.poll_events(&mut observer);
        std::thread::sleep(std::time::Duration::from_secs(2));
    }
}
