[package]
name = "nodesea-bt"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
readme = "README.md"

[dependencies]
anyhow.workspace = true
tokio.workspace = true
bitflags = "2.13.1"
cxx = "1.0.199"
hex = "0.4.3"
thiserror = "2.0.20"
bytes = "1.12.1"

[build-dependencies]
cmake = "0.1.58"
cxx-build = "1.0.199"
